---
title: "Texas Power Crisis, February 2021"
author: "Jaslyn Miura"
format: html
date: October 24, 2025
editor_options: 
  chunk_output_type: console
warning: false
message: false
---

```{r, echo=FALSE}
# load in necessary packages
library(terra)
library(tidyverse)
library(tmap) 
library(kableExtra) 
library(stars)
library(sf)
```

### Load in data and data cleaning
```{r}
# read in VIIRS night light data
lights1_07 <- read_stars("data/VNP46A1/VNP46A1.A2021038.h08v05.001.2021039064328.tif")
lights2_07 <- read_stars("data/VNP46A1/VNP46A1.A2021038.h08v06.001.2021039064329.tif")
lights1_16 <- read_stars("data/VNP46A1/VNP46A1.A2021047.h08v05.001.2021048091106.tif")
lights2_16 <- read_stars("data/VNP46A1/VNP46A1.A2021047.h08v06.001.2021048091105.tif")

# read in OSM roads data
roads <- st_read("data/gis_osm_roads_free_1.gpkg", 
                 query = "SELECT * FROM gis_osm_roads_free_1 WHERE fclass='motorway'")

# read in OSM houses data
houses <- st_read("data/gis_osm_buildings_a_free_1.gpkg", query = "SELECT *
FROM gis_osm_buildings_a_free_1
WHERE (type IS NULL AND name IS NULL)
OR type in ('residential', 'apartments', 'house', 'static_caravan', 'detached')")

# read in ACS socioeconomic data
ACS_geometry <- st_read("data/ACS_2019_5YR_TRACT_48_TEXAS.gdb", layer = 'ACS_2019_5YR_TRACT_48_TEXAS') 
ACS_attributes <- st_read("data/ACS_2019_5YR_TRACT_48_TEXAS.gdb", layer = "X19_INCOME") 

# joining the ACS geometry and attribute data
ACS_join <- left_join(ACS_geometry, ACS_attributes, by = c("GEOID_Data" = "GEOID"))

```

```{r}

# Get information about the layers in 'my_spatial_data.gpkg'
layer_info <- st_layers(dsn = "data/ACS_2019_5YR_TRACT_48_TEXAS.gdb")

# Print the layer information
print(layer_info)
```

```{r}

# joining the night light rasters of the same day.
lights_07 <- st_mosaic(lights1_07, lights2_07)
lights_16 <- st_mosaic(lights1_16, lights2_16)

# creating a raster of the change in night light intensity.
blackout <- (lights_07 - lights_16)

```

```{r}

# Creating a bbox of the area of study, Houston.
houston_bbox <- st_bbox(c(xmin = -94.5, ymin = 29, xmax = -96.5, ymax = 30.5), 
                        crs = st_crs(4326))

# Checking that the crs of the blackout raster and the crs of the bbox match.
if(st_crs(blackout) == st_crs(houston_bbox)){
  print("it's a match!")
} else {
  print("crs does not match")
}

# Using the houston_bbox to crop the blackout raster to the area of study.
houston_cropped <- st_crop(blackout, houston_bbox)

```


```{r}

# Create raster mask of the same resolution and extent
blackout_mask <- houston_cropped

# Setting the values in the mask raster that are less than 200 to be NA values
blackout_mask[blackout_mask < 200] <- NA

# Vectorizing the masked raster
masked_sf <- blackout_mask %>% 
  st_as_sf() %>% 
  st_make_valid()

# Mapping the raster to see if it works
tm_shape(masked_sf) +
  tm_polygons()

### THIS WORKS!!!!

```

```{r}

# Setting the crs of of the mask vector.
houston_transformed <- st_transform(masked_sf, crs = st_crs(3083))

tm_shape(houston_transformed) +
  tm_polygons()

```

```{r}

# Checking that the crs of the roads and the crs of the houston_transformed vector match.
if(st_crs(roads) == st_crs(houston_transformed)){
  print("it's a match!")
} else {
  print("crs does not match")
}

# Setting the crs of roads to match the crs of houston_transformed.
roads <- st_transform(roads, crs = st_crs(houston_transformed))

# Using houston_transfomed to crop the roads.
roads_cropped <- st_crop(roads, houston_transformed)

tm_shape(houston_transformed) +
  tm_polygons() +
  tm_shape(roads_cropped) +
  tm_lines() +
  tm_title(text = "Blackout Transformed vector")

```

```{r}

# Creating a 200m buffer around all highways.
highways_buff_200m <- st_buffer(roads_cropped, dist = 200)

tm_shape(houston_transformed) +
  tm_polygons() +
  tm_shape(highways_buff_200m) +
  tm_polygons()

# Combining the buffer geometries and creating one buffer shape.
highways_buff_union <- st_union(highways_buff_200m) %>% 
  st_as_sf()

tm_shape(highways_buff_union) +
  tm_polygons() 

```

```{r}

# Filtering under the st_disjoint predicate to find blackout areas outside of the buffer 
outside_roads <- houston_transformed %>%
  st_filter(y = highways_buff_union, .predicate = st_disjoint) 

tm_shape(outside_roads) +
  tm_polygons() 


# everything above works!!!!
```

# houses likely impacted by blackout
```{r}

# Checking that the crs of the housed and the crs of the outside_roads vector match.
if(st_crs(houses) == st_crs(outside_roads)){
  print("it's a match!")
} else {
  print("crs does not a match")
}

# Setting the crs of houses to match the crs of outside_roads.
houses <- st_transform(houses, crs = st_crs(outside_roads))

# Filtering under the st_intersects predicate to find the houses in the blackout region.
outside_roads_houses <- houses %>%
  st_filter(y = outside_roads, .predicate = st_intersects)

tm_shape(outside_roads_houses) +
  tm_polygons()

```


```{r}
# NEED TO ADD THIS TO THE DATA CLEANING PART ABOVE.
ACS_join <- ACS_join %>% 
  select("B19013e1", "B19013m1", "GEOID", "Shape") 


# Checking that the crs of the housed and the crs of the outside_roads vector match.
if(st_crs(ACS_join) == st_crs(outside_roads_houses)){
  print("it's a match!")
} else {
  print("crs does not a match")
}

ACS_join <- st_transform(ACS_join, crs = st_crs(outside_roads_houses))

# Using houston_transfomed to crop the ACS_join
ACS_crop <- st_crop(ACS_join, outside_roads_houses)

# Census blocks that have experienced the blackout
outside_roads_houses <- ACS_crop %>%
  st_filter(y = outside_roads_houses, .predicate = st_intersects)

tm_shape(ACS_crop) +
  tm_polygons() +
tm_shape(outside_roads_houses) +
  tm_polygons(fill = "hotpink") +
  tm_title(text = "Census blocks that experienced blackout")

```

```{r}

census_no_blackout <- ACS_crop %>%
  st_filter(y = outside_roads_houses, .predicate = st_intersects, .reverse = TRUE)

# outside_roads_houses_union <- st_union(outside_roads_houses)
# 
# census_no_blackout <- ACS_crop %>%
#   st_filter(y = outside_roads_houses, .predicate = st_difference)

# outside_roads_houses <- ACS_crop %>%
#   st_filter(y = census_no_blackout, .predicate = st_intersects)

# --------



tm_shape(ACS_crop) +
  tm_polygons(fill = "dodgerblue") + 
  tm_shape(census_no_blackout) +
  tm_polygons(fill = "hotpink") 

```

